treatments:
  - name: debugGame1
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - esHfQ4tdiYg4mf5TR
      - y9Gosgtt6TjtRwDtu
      - dymEsC3e744QWe4Bm
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
  - name: debugGame
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - P5vCxewiYFW9Ni5kA
      - dymEsC3e744QWe4Bm
      - y9Gosgtt6TjtRwDtu
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - oEr7fJ8qbFpx5gEYe
  - name: debugResults
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - P5vCxewiYFW9Ni5kA
      - y9Gosgtt6TjtRwDtu
      - dymEsC3e744QWe4Bm
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - oEr7fJ8qbFpx5gEYe
      - cW64McFbC842SYi2q
  - name: debugGame2
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - P5vCxewiYFW9Ni5kA
      - y9Gosgtt6TjtRwDtu
      - dymEsC3e744QWe4Bm
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - oEr7fJ8qbFpx5gEYe
      - oXN8zgB2YZaxd66F6
  - name: debugGame3
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - esHfQ4tdiYg4mf5TR
      - y9Gosgtt6TjtRwDtu
      - dymEsC3e744QWe4Bm
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - oEr7fJ8qbFpx5gEYe
      - cW64McFbC842SYi2q
      - mXoRMd2xwprmjNebw
      - 2pjpjsGz6mM5kMWdQ
      - eSSwhh5jaXazv4sgf
  - name: debugGame2Passive
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - esHfQ4tdiYg4mf5TR
      - y9Gosgtt6TjtRwDtu
      - dymEsC3e744QWe4Bm
      - aAJmSP59JoHtH7349
      - rXSaahKKZZywcroeH
      - XZ4c7B3c7L3QzRhir
      - oEr7fJ8qbFpx5gEYe
      - RbSWb6bnsbe3z9w32
      - cW64McFbC842SYi2q
      - mXoRMd2xwprmjNebw
      - 2A6ocPbuXKpv6ryLm
      - 2pjpjsGz6mM5kMWdQ
  - name: debugGame1Passive
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - esHfQ4tdiYg4mf5TR
      - dymEsC3e744QWe4Bm
      - y9Gosgtt6TjtRwDtu
      - 8ckNEwEvcv9TMoJ9Z
      - rXSaahKKZZywcroeH
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - oEr7fJ8qbFpx5gEYe
      - cW64McFbC842SYi2q
      - mXoRMd2xwprmjNebw
      - 2pjpjsGz6mM5kMWdQ
      - 2A6ocPbuXKpv6ryLm
  - name: debugGamePassive2
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - esHfQ4tdiYg4mf5TR
      - y9Gosgtt6TjtRwDtu
      - dymEsC3e744QWe4Bm
      - aAJmSP59JoHtH7349
      - rXSaahKKZZywcroeH
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - oEr7fJ8qbFpx5gEYe
      - oXN8zgB2YZaxd66F6
      - mXoRMd2xwprmjNebw
      - 2pjpjsGz6mM5kMWdQ
      - 2A6ocPbuXKpv6ryLm
      - MQRaDBS543CmejQL3
  - name: debugSpeakerInactive
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - P5vCxewiYFW9Ni5kA
      - seEj7L8875x6vLcSF
      - dymEsC3e744QWe4Bm
      - rXSaahKKZZywcroeH
      - aAJmSP59JoHtH7349
      - XZ4c7B3c7L3QzRhir
      - XSkxthG9wfrD49Ja5
      - oEr7fJ8qbFpx5gEYe
      - oXN8zgB2YZaxd66F6
      - mXoRMd2xwprmjNebw
      - 2pjpjsGz6mM5kMWdQ
      - 2A6ocPbuXKpv6ryLm
      - MQRaDBS543CmejQL3
  - name: testGame1
    factorIds:
      - dLsDaQ4ppNjpQx7jC
      - PGGiMn4xNmrZrdHCy
      - esHfQ4tdiYg4mf5TR
      - G3rpTZPw9BxDZjLR2
      - HuJseEdBRcpCQ4RFG
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - L4sx4p3AigdqqBwiH
      - yJbFmfSu8HM38EkdQ
      - NmdAZJNdkMbW3mvuq
      - NPyvr2b5wHokeiCie
  - name: testGame2
    factorIds:
      - dLsDaQ4ppNjpQx7jC
      - PGGiMn4xNmrZrdHCy
      - esHfQ4tdiYg4mf5TR
      - G3rpTZPw9BxDZjLR2
      - HuJseEdBRcpCQ4RFG
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - L4sx4p3AigdqqBwiH
      - yJbFmfSu8HM38EkdQ
      - MQRaDBS543CmejQL3
      - NPyvr2b5wHokeiCie
  - name: testGame3
    factorIds:
      - dLsDaQ4ppNjpQx7jC
      - PGGiMn4xNmrZrdHCy
      - esHfQ4tdiYg4mf5TR
      - G3rpTZPw9BxDZjLR2
      - HuJseEdBRcpCQ4RFG
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - L4sx4p3AigdqqBwiH
      - yJbFmfSu8HM38EkdQ
      - MQRaDBS543CmejQL3
      - dXXH9dhgDZLEWRFRG
  - name: activeAdvisors_6P_Debug
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - P5vCxewiYFW9Ni5kA
      - y9Gosgtt6TjtRwDtu
      - dymEsC3e744QWe4Bm
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - L4sx4p3AigdqqBwiH
      - oXN8zgB2YZaxd66F6
      - aHgqinwhL7KNt8KvT
      - JBZckugCCfvX9aSye
      - eSSwhh5jaXazv4sgf
      - NmdAZJNdkMbW3mvuq
      - dXXH9dhgDZLEWRFRG
  - name: activeAdvisors_6P
    factorIds:
      - YJf3w33stc6maF5L5
      - QCBsQhfoia2qSktWq
      - esHfQ4tdiYg4mf5TR
      - G3rpTZPw9BxDZjLR2
      - HuJseEdBRcpCQ4RFG
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - L4sx4p3AigdqqBwiH
      - yJbFmfSu8HM38EkdQ
      - aHgqinwhL7KNt8KvT
      - JBZckugCCfvX9aSye
      - eSSwhh5jaXazv4sgf
      - NmdAZJNdkMbW3mvuq
      - dXXH9dhgDZLEWRFRG
  - name: passiveAdvisors_4P
    factorIds:
      - dLsDaQ4ppNjpQx7jC
      - PGGiMn4xNmrZrdHCy
      - esHfQ4tdiYg4mf5TR
      - G3rpTZPw9BxDZjLR2
      - HuJseEdBRcpCQ4RFG
      - aAJmSP59JoHtH7349
      - mteWcmPNzGJ7PiNDg
      - XZ4c7B3c7L3QzRhir
      - RbSWb6bnsbe3z9w32
      - L4sx4p3AigdqqBwiH
      - yJbFmfSu8HM38EkdQ
      - aHgqinwhL7KNt8KvT
      - JBZckugCCfvX9aSye
      - eSSwhh5jaXazv4sgf
      - MQRaDBS543CmejQL3
      - dXXH9dhgDZLEWRFRG
factorTypes:
  - _id: D6JRKsrw4cebdypZX
    name: playerCount
    description: The Number of players participating in the given game.
    required: true
    type: Integer
    min: 1
  - _id: uj7xmZrn9suPsaYfn
    name: networkStructure
    description: >-
      Determines which players are connected to which players. Connections
      between two players correlate to potential speaker-listener or
      listener-advisor pairs. The format of the structure is a string where
      connections between two different player nodes are separated by a hyphen (
      - ), and different connections are separated by a comma ( , ) . For
      example, "1-2, 1-3" means that player 1 has connections to both player 2
      and 3. Player roles are chosen randomly within the game.
    required: true
    type: String
    min: 0
    max: 99999
  - _id: aJr3d7oPHGLYPbKsa
    name: numTaskRounds
    description: >-
      Number of task rounds in a game. Task rounds are rounds where speaker
      players describe a symbol to the listeners. Then, the listeners pick the
      symbol that best corresponds to the given description. Listeners may
      receive help from advisors they are paired with.
    required: false
    type: String
    min: 0
    max: 999
  - _id: MztnxcttSG5mnTbj5
    name: tellDuration
    description: >-
      Duration of time (in seconds) that speakers get to describe their
      respective selected symbol. If this duration passes, the stage will end.
    required: true
    type: Integer
    min: 0
    max: 99999
  - _id: yQ7BmiyhKNNseRyJs
    name: listenDuration
    description: >-
      Duration of time (in seconds) that listeners and advisors get to choose
      the symbol that best corresponds to the description the speaker gave. If
      this duration passes, the stage will end.
    required: true
    type: Integer
    min: 0
    max: 99999
  - _id: qAcKZLgvtcRiFpayW
    name: numAdvisorsPerPair
    description: The number of advisors that are paired with each listener.
    required: true
    type: Integer
    min: 0
    max: 999
  - _id: spyhef2BPce8EhJjH
    name: numSLPairs
    description: Number of speaker-listener pairs that are chosen for a given round.
    required: true
    type: Integer
    min: 0
    max: 999
  - _id: NNPK2pkJhA26rXJhL
    name: reqMutual
    description: >-
      If true, advisors are required to be a mutual connection to both the
      speaker and listener. Otherwise, advisors only need to be connected to the
      listener.
    required: true
    type: Boolean
  - _id: DtmwSjC5BTqxJN2p7
    name: numSurveyRounds
    description: >-
      Number of survey rounds in a game. Survey rounds are rounds where all
      players answer a brief survey about the game. These surveys will be evenly
      placed throughout the entire game. Survey rounds are done asynchronously.
    required: true
    type: Number
    min: 0
    max: 999
  - _id: ahdE3JQ8Hp3us8Tw2
    name: surveyDuration
    description: >-
      Duration of time (in seconds) that players are allowed to complete the
      mid-game surveys. If this duration passes, the stage will end.
    required: true
    type: Number
    min: 0
    max: 99999
  - _id: w4maXJF8TALxAh4sP
    name: resultsDuration
    description: >-
      Duration of time (in seconds) that players get to review their results for
      the round. If this duration passes, the stage will end.
    required: true
    type: Integer
    min: 0
    max: 99999
  - _id: MRahb4YkEEXeY97SL
    name: slReward
    description: >-
      Reward (in dollars) given to a speaker-listener pair when they
      successfully coordinate on a symbol.
    required: false
    type: Number
    min: 0
    max: 9999
  - _id: ebFC2PYpWhnamGGte
    name: advisorReward
    description: >-
      Reward (in dollars) given to an advisor when they successfully choose the
      symbol.
    required: false
    type: Number
    min: 0
    max: 9999
  - _id: QaQ7Dis5nZbJdEiDL
    name: slPenalty
    description: >-
      Penalty (in dollars) given to a speaker-listener pair when they do not
      successfully coordinate on a symbol.
    required: false
    type: Number
    min: 0
    max: 9999
  - _id: BTeppDTwQBzDPc8xX
    name: passiveMode
    description: >-
      True, if passive advisors are used in the game. False, if active advisors
      are used in the game.
    required: true
    type: Boolean
  - _id: 5vXH9pCHHRgxHMWXH
    name: passiveDuration
    description: >-
      Duration of time (in seconds) that players get to review their passive
      results for the round. If this duration passes, the stage will end.
    required: false
    type: Integer
    min: 0
    max: 99999
    archivedAt: 2023-04-14T12:45:25.899Z
  - _id: 5SvJPPb26JFLhKCAM
    name: passiveResultsDuration
    description: >-
      Duration of time (in seconds) that players get to review their passive
      results for the round. If this duration passes, the stage will end.
    required: false
    type: Number
    min: 0
    max: 99999
factors:
  - _id: 7yM6QYFqyTuzrT3jw
    name: 'true'
    value: true
    factorTypeId: NNPK2pkJhA26rXJhL
  - _id: XZ4c7B3c7L3QzRhir
    name: 'false'
    value: false
    factorTypeId: NNPK2pkJhA26rXJhL
  - _id: mteWcmPNzGJ7PiNDg
    name: two
    value: 2
    factorTypeId: spyhef2BPce8EhJjH
  - _id: YJf3w33stc6maF5L5
    name: six
    value: 6
    factorTypeId: D6JRKsrw4cebdypZX
  - _id: esHfQ4tdiYg4mf5TR
    name: five
    value: '5'
    factorTypeId: aJr3d7oPHGLYPbKsa
  - _id: DoBp7Jp7mY2yvQoDj
    name: one
    value: '1'
    factorTypeId: aJr3d7oPHGLYPbKsa
  - _id: seEj7L8875x6vLcSF
    name: oneMinute
    value: 60
    factorTypeId: MztnxcttSG5mnTbj5
  - _id: AGQAiSopmaWgozWqm
    name: oneMinute
    value: 60
    factorTypeId: yQ7BmiyhKNNseRyJs
  - _id: dymEsC3e744QWe4Bm
    name: veryLong
    value: 99999
    factorTypeId: yQ7BmiyhKNNseRyJs
  - _id: y9Gosgtt6TjtRwDtu
    name: veryLong
    value: 99999
    factorTypeId: MztnxcttSG5mnTbj5
  - _id: aAJmSP59JoHtH7349
    name: two
    value: 2
    factorTypeId: qAcKZLgvtcRiFpayW
  - _id: 8ckNEwEvcv9TMoJ9Z
    name: one
    value: 1
    factorTypeId: qAcKZLgvtcRiFpayW
  - _id: zuREEcisTBXWs9qKa
    name: one
    value: 1
    factorTypeId: spyhef2BPce8EhJjH
  - _id: QCBsQhfoia2qSktWq
    name: sixPlayerFC
    value: >-
      1-2, 1-3, 1-4, 1-5, 1-6, 2-1, 2-3, 2-4, 2-5, 2-6, 3-1, 3-2, 3-4, 3-5, 3-6,
      4-1, 4-2, 4-3, 4-5, 4-6, 5-1, 5-2, 5-3, 5-4, 5-6, 6-1, 6-2, 6-3, 6-4, 6-5
    factorTypeId: uj7xmZrn9suPsaYfn
  - _id: RbSWb6bnsbe3z9w32
    name: two
    value: 2
    factorTypeId: DtmwSjC5BTqxJN2p7
  - _id: XSkxthG9wfrD49Ja5
    name: three
    value: 3
    factorTypeId: DtmwSjC5BTqxJN2p7
  - _id: P5vCxewiYFW9Ni5kA
    name: six
    value: '6'
    factorTypeId: aJr3d7oPHGLYPbKsa
  - _id: oEr7fJ8qbFpx5gEYe
    name: veryLong
    value: 99999
    factorTypeId: ahdE3JQ8Hp3us8Tw2
  - _id: L4sx4p3AigdqqBwiH
    name: tenMinutes
    value: 600
    factorTypeId: ahdE3JQ8Hp3us8Tw2
  - _id: oXN8zgB2YZaxd66F6
    name: tenSeconds
    value: 10
    factorTypeId: w4maXJF8TALxAh4sP
  - _id: cW64McFbC842SYi2q
    name: veryLong
    value: 99999
    factorTypeId: w4maXJF8TALxAh4sP
  - _id: mXoRMd2xwprmjNebw
    name: quarter
    value: 0.25
    factorTypeId: MRahb4YkEEXeY97SL
  - _id: aHgqinwhL7KNt8KvT
    name: dime
    value: 0.1
    factorTypeId: MRahb4YkEEXeY97SL
  - _id: 2pjpjsGz6mM5kMWdQ
    name: dime
    value: 0.1
    factorTypeId: ebFC2PYpWhnamGGte
  - _id: JBZckugCCfvX9aSye
    name: nickel
    value: 0.05
    factorTypeId: ebFC2PYpWhnamGGte
  - _id: eSSwhh5jaXazv4sgf
    name: penny
    value: 0.01
    factorTypeId: QaQ7Dis5nZbJdEiDL
  - _id: 2A6ocPbuXKpv6ryLm
    name: nickel
    value: 0.05
    factorTypeId: QaQ7Dis5nZbJdEiDL
  - _id: rXSaahKKZZywcroeH
    name: three
    value: 3
    factorTypeId: spyhef2BPce8EhJjH
  - _id: MQRaDBS543CmejQL3
    name: 'true'
    value: true
    factorTypeId: BTeppDTwQBzDPc8xX
  - _id: NmdAZJNdkMbW3mvuq
    name: 'false'
    value: false
    factorTypeId: BTeppDTwQBzDPc8xX
  - _id: dLsDaQ4ppNjpQx7jC
    name: four
    value: 4
    factorTypeId: D6JRKsrw4cebdypZX
  - _id: PGGiMn4xNmrZrdHCy
    name: fourPlayerFC
    value: '1-2, 1-3, 1-4, 2-1, 2-3, 2-4, 3-1, 3-2, 3-4, 4-1, 4-2, 4-3'
    factorTypeId: uj7xmZrn9suPsaYfn
  - _id: G3rpTZPw9BxDZjLR2
    name: thirtySeconds
    value: 30
    factorTypeId: MztnxcttSG5mnTbj5
  - _id: HuJseEdBRcpCQ4RFG
    name: thirtySeconds
    value: 30
    factorTypeId: yQ7BmiyhKNNseRyJs
  - _id: evwtdX99rgAomsbhw
    name: resultsDuration
    value: 5
    factorTypeId: w4maXJF8TALxAh4sP
    archivedAt: 2023-04-14T12:31:01.841Z
  - _id: yJbFmfSu8HM38EkdQ
    name: sixSeconds
    value: 6
    factorTypeId: w4maXJF8TALxAh4sP
  - _id: NPyvr2b5wHokeiCie
    name: sevenSeconds
    value: 7
    factorTypeId: 5vXH9pCHHRgxHMWXH
  - _id: dXXH9dhgDZLEWRFRG
    name: sevenSeconds
    value: 7
    factorTypeId: 5SvJPPb26JFLhKCAM
lobbyConfigs:
  - name: Default
    timeoutType: lobby
    timeoutInSeconds: 600
    timeoutStrategy: fail
    gameLobbyIds: []
